env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
overrides: []
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'
rules: { no-promise-executor-return: 'off', '@typescript-eslint/no-unused-vars': 'off', no-async-promise-executor: 'off', '@typescript-eslint/no-explicit-any': 'off', no-constant-condition: 'off' }
